version: '3'
services:
    load_balancer:
        image: haproxy
        ports: 
            - 8088:8080
        volumes: 
            - ./haproxy:/usr/local/etc/haproxy
    node1:
        container_name: node1
        build: .
        environment: 
            - PORT=5000
        ports: 
            - 5000:5000
        command: bash -c " 
                npm i
                && npm start"
        volumes: 
            - ./src:/app/src

    node2:
        container_name: node2
        build: .
        environment: 
            - PORT=7000
        ports: 
            - 7000:7000
        command: bash -c " 
                npm i
                && npm start"
        volumes: 
            - ./src:/app/src

    node3:
        container_name: node3
        build: .
        environment: 
            - PORT=9000
        ports: 
            - 9000:9000
        command: bash -c " 
                npm i
                && npm start"
        volumes: 
            - ./src:/app/src