version: '3'
services:
    node:
        container_name: api_server
        build: .
        ports: 
            - 5000:5000
        command: bash -c " 
                npm i
                && npm start
            "
        volumes: 
            - ./src:/app/src
